### PR TITLE
deploy HF notebooks

### PR DESCRIPTION
**Pull request by rahult-graphcore**
Use automated deployment script to copy everything in the forked optimum repo's "notebooks" folder into the forked gradient GC-HF repo's "notebook-tutorials" folder.

### CODE REVIEW

**Review by payoto — COMMENTED** [review]
Can you point me to the version of the deployment script that you used?

**Comment by rahult-graphcore** [comment]
> Can you point me to the version of the deployment script that you used?

In the `save-artifacts` branch: https://github.com/graphcore/paperspace-automation/blob/save-artifacts/deployment/deploy.py

**Comment by payoto** [comment]
Sorry, I meant the Yaml file you used!

**Comment by rahult-graphcore** [comment]
I created one, it's not committed anywhere:

```
files:
  source:
    paths:
    - expression: '*'
      path: notebooks
      recursive: true
    repository:
      origin: ../../optimum-graphcore-fork
      prefix: notebooks
      ref: main
  target:
    renames: {}
    repository:
      origin: ../../Graphcore-HuggingFace-fork
      prefix: notebook-tutorials/
      ref: prepare-sdk-release-3.0-deployHF
```

**Comment by rahult-graphcore** [comment]
Running deployment again, will recreate PR

**Pull request closed without merging**
