### PR TITLE
Prepare sdk release 3.0

### PR DESCRIPTION
**Pull request by payoto**

### CODE REVIEW

**Comment by rahult-graphcore** [comment]
Deployed/Updated HF notebooks in commit [6d8edcf](https://github.com/graphcore/Graphcore-HuggingFace-fork/pull/8/commits/6d8edcf2e7d71656f19f165a0ac19a0c7230e7d4) using yaml file: https://github.com/graphcore/paperspace-automation/blob/67b1ceb8da37efe2387e2958222e35045fa43448/releases/3.0.0/deploy-huggingface-paperspace.yaml

**Comment by rahult-graphcore** [comment]
Commit [046bc60](https://github.com/graphcore/Graphcore-HuggingFace-fork/pull/8/commits/046bc60e4399ba5f0dd091396210923f307b0e3b) consists of pulled changes from phabricator for ViT model, using yaml file: https://github.com/graphcore/paperspace-automation/blob/cf393761d667854a55d22ce332e920c5fe3de9a5/releases/3.0.0/deploy-huggingface-paperspace.yaml

**Comment by rahult-graphcore** [comment]
Commit [565394d](https://github.com/graphcore/Graphcore-HuggingFace-fork/pull/8/commits/565394de392fc22abd7d82e5eddfb743e4d44a3a) moves stable diffusion to the root directory, using yaml: https://github.com/graphcore/paperspace-automation/commit/4e4b5b852de46ebc8f392143d2e996eb003263ec

**Comment by payoto** [comment]
Involving @nmb-paperspace

**Comment by nmb-paperspace** [comment]
FYI I've reviewed the commits on this repo branch, seeing the various .ipynb, setup.sh, etc., changes.

Looks like a good set of updates. I can understand most of them, but not all of the ones concerning the back-end repo/HF infrastructure. So don't count me as an approver for those when we merge this branch to main.

Nothing jumped out as urgent that I don't cover in my updates to the shared_graphcore-paperspace Slack channel, so no comments on this PR directly as of now.

**Comment by payoto** [comment]
Closing to open pull request on upstream

**Pull request closed without merging**
